### ISSUE TITLE
Save not showing save name

### ISSUE THREAD

**Issue by Lazyboy38** [SebLague/Digital-Logic-Sim#1]
It might just be me and a small screen on my laptop but if i want to load a file it seems like its shows a path and the actual "projectname" is cut out 
![Digital_Logic_Sim_e5tA7aUaV6](https://user-images.githubusercontent.com/1630464/100928684-d07e6980-34e6-11eb-9a61-911b5e547252.png)

**Comment by SebLague** [comment]
Thanks for letting me know, should be fixed now if you download again.
