### ISSUE TITLE
Can't edit or delete created chips

### ISSUE THREAD

**Issue by MagusOscuro** [SebLague/Digital-Logic-Sim#10]
Being unable to edit or delete a created chip makes it somewhat difficult to start something and return to it later.

**Comment by jampen** [comment]
Working on it

**Comment by Broken-Admin** [comment]
In the meantime, where are save files stored, glancing over the save code on my phone they seem to be stored in plaintext but I'm lost as to where they are stored.

Personally I'm running the Linux version, but I'd be quite happy to submit a PR for a markdown document with more information about all systems, as I mentioned in #15.

**Comment by mathias234** [comment]
> In the meantime, where are save files stored, glancing over the save code on my phone they seem to be stored in plaintext but I'm lost as to where they are stored.
> 
> Personally I'm running the Linux version, but I'd be quite happy to submit a PR for a markdown document with more information about all systems, as I mentioned in #15.
SaveData is stored here for the built game.
`AppData\LocalLow\Sebastian Lague\Digital Logic Sim\SaveData`

**Comment by Broken-Admin** [comment]
Appdata? I believe you're failing to entertain the fact that I am running the Linux version. Or is there a further absolute path?

**Comment by mathias234** [comment]
> Appdata? I believe you're failing to entertain the fact that I am running the Linux version. Or is there a further absolute path, although you seem to have provided a backslashed path?
> 
> Additionally, isn't the path typically `%APPDATA%`?

Take a look at this post, it contains all the locations for each operating system...
https://stackoverflow.com/a/44421935

**Comment by CursedFlames** [comment]
A way of reordering them would also be nice.

**Comment by Broken-Admin** [comment]
Agreed, I may work on a PR tomorrow.

**Comment by davidkowalk** [comment]
I would suggest that right clicking on a chip opens a menu that gives you the option to either delete a chip and all of its dependants or load the chip-layout into the main window.

The chip saves all of the data from the main window anyway.

**Comment by willcatmeow** [comment]
> Appdata? I believe you're failing to entertain the fact that I am running the Linux version. Or is there a further absolute path, although you seem to have provided a backslashed path?
> 
> Additionally, isn't the path typically `%APPDATA%`?

well, adding the `%`'s on the ends is telling the computer to go to c:\users\`username`\appdata\roaming,
so since the directory is not going to roaming it doesn't go there and it is a windows directory, but the person who typed it decided that they would skip the front end.

**Comment by marco-trovato** [comment]
Someone made [this fork](https://github.com/gml16/Digital-Logic-Sim) with **edit chip** option. I wish this feature it was included in the main branch

**Comment by marco-trovato** [comment]
Unfortunately there is no release, is anybody able to compile it?

Version with edit chip: https://github.com/gml16/Digital-Logic-Sim

**Comment by okyloky9** [comment]
> Unfortunately there is no release, is anybody able to compile it?
> 
> Version with edit chip: https://github.com/gml16/Digital-Logic-Sim

There's a windows build in this post now because people had been asking for it. It's at the bottom of this pull:
https://github.com/SebLague/Digital-Logic-Sim/pull/36

**Comment by DerpyTurtle1000** [comment]
how do i delete chips and projects on mac?

**Comment by thetayloredman** [comment]
> how do i delete chips and projects on mac?

You can't do either at this time.

You can manually remove the project by going to `~/Library/Application Support/Sebastian Lague/Digital Logic Sim/SaveData` and deleting the folder with the project name if you *really* need to remove a project.
