### ISSUE TITLE
chips not outputting when saving? repost

### ISSUE THREAD

**Issue by technikhea** [SebLague/Digital-Logic-Sim#100]
ok i wanna repost this because i ran in this problem and other's already had the problem! (2) but no one answered it so i wanna repost this:
my problem is that i want to create a CPU i have a clock for reading code in there and when i test it it works fine but when i save it as a chip it just doesn't output something tried 10 recreations new name doesn't work.
someone please help me why this isn't working

**Comment by technikhea** [comment]
someone pls help finally

**Comment by Turnip1234** [comment]
You'll have to provide a clock input to the chip, rather than having the clock embedded because unfortunately self-contained circuits like clocks don't automatically run when you start the simulation

**Comment by technikhea** [comment]
i know i know found another way already but thanks
