### ISSUE TITLE
linux

### ISSUE THREAD

**Issue by zachariahstauffer** [SebLague/Digital-Logic-Sim#101]
How do i run this on linux.

**Comment by technikhea** [comment]
idk

**Comment by BBQGiraffe** [comment]
the Linux download is available on the itch.io page
[](https://sebastian.itch.io/digital-logic-sim)

**Comment by zachariahstauffer** [comment]
![image](https://user-images.githubusercontent.com/100742502/176860568-a1361f3f-806d-444b-bfa0-ae019d2b2d39.png)
I got this far and I don't know what else to do

**Comment by zachariahstauffer** [comment]
i renamed the green one

**Comment by zachariahstauffer** [comment]
> iirc there should just be an executable file in there that you can run with `./[filename]` you might have to run `chmod +x [filename]` to make it executable

how do i know what file it is

**Comment by zachariahstauffer** [comment]
![image](https://user-images.githubusercontent.com/100742502/176863826-c683760f-8c78-4085-b124-d8823d0b4f0a.png)

**Comment by zachariahstauffer** [comment]
@SebLague

**Comment by Turnip1234** [comment]
`./Digital\ Logic\ Sim x86_64` (I *think* you have to backslash the spaces but I could be mistaken)
no need to @mention anyone

**Comment by zachariahstauffer** [comment]
doesn't work for me
i could be doing something wrong

![image](https://user-images.githubusercontent.com/100742502/176865712-08f25e3e-c1dd-418c-b3d2-eae2ef2e3607.png)

**Comment by Turnip1234** [comment]
yeah I misspelled the file name check my comment again

**Comment by zachariahstauffer** [comment]
![image](https://user-images.githubusercontent.com/100742502/176865910-590a4d9c-a55a-4d70-b519-7220956b88b1.png)

**Comment by zachariahstauffer** [comment]
permission denied

**Comment by zachariahstauffer** [comment]
got it thanks

**Comment by joe733** [comment]
ref: https://github.com/SebLague/Digital-Logic-Sim/issues/109#issuecomment-1271409881
