### ISSUE TITLE
how do i delete a chip?

### ISSUE THREAD

**Issue by cleverdumb** [SebLague/Digital-Logic-Sim#102]
how do i delete a chip? i made a mistake in one of them and now i need to delete it

**Comment by Turnip1234** [comment]
Go to the saves folder (%appdata%\..\LocalLow\Sebastian Lague\Digital Logic Sim) and then there's a saves folder in there, with txt files for each chip
delete the txt file, and restart the game

**Comment by cleverdumb** [comment]
ok thx
