### ISSUE TITLE
crazy GPU usage

### ISSUE THREAD

**Issue by waynezhang2021** [SebLague/Digital-Logic-Sim#107]
It is very crazy. Once I start this version of DLS, my GPU looks like this:
![image](https://user-images.githubusercontent.com/93867250/187320250-59561349-f08a-4887-8f04-352f8f864df7.png)
This is normal temp:
![image](https://user-images.githubusercontent.com/93867250/187319671-2bb6a3dd-63b3-403f-83dd-41df2d6591bf.png)
Just on for a minute and the temperature simply rises super quickly to 50°C……
task manager:
![image](https://user-images.githubusercontent.com/93867250/187320872-10ea231c-06bd-4f63-92cb-348486c95c15.png)
on startup:
![image](https://user-images.githubusercontent.com/93867250/187320794-3a3de43e-23fb-482e-aef5-30beeb97dc7c.png)
![image](https://user-images.githubusercontent.com/93867250/187320819-108e183f-848d-4a68-a739-ca96a4c48dbd.png)
I don't understand why this will happen……Is it kind of anti-aliasing?

**Comment by Xanderplayz17** [comment]
Huh.
Seems like the GPU you are using is very slow when rendering 3D.
I have no idea why this gam- ugh simulation is 3D
