### ISSUE TITLE
Why is my digital display showing -8 instead of 8 and -8 instead of 15 and probably a lot more things...

### ISSUE THREAD

**Issue by Kaminester** [SebLague/Digital-Logic-Sim#108]
![image](https://user-images.githubusercontent.com/91369681/188248693-f85ff4eb-23dd-4bec-9a9c-aa3a5f2b2c96.png)

**Comment by Turnip1234** [comment]
You're trying to display an unsigned number on a signed display, if you're confused about what that means check out the "Two's Compliment" section of Sebastian Lague's first video in the two part series using Digital Logic Sim.

For a quick fix, make the number output again and uncheck "signed" (I think that's what the checkbox is called).
