### ISSUE TITLE
trouble with running linux

### ISSUE THREAD

**Issue by Bigbfromcle** [SebLague/Digital-Logic-Sim#109]
I'm new to linux and can't figure out how to start the file. I am on a chromebook with linux installed and I was wondering if someone could give me a copy and paste command to run it. I've seen some other posts about it but I'm still not sure how to run it. The exact file names are below. Keep in mind I don;t know anything on how linux uses quotation marks, parentheses, etc
![image](https://user-images.githubusercontent.com/97521603/194201643-1ebdb9da-b0d7-4548-992d-277d659a017b.png)

**Comment by joe733** [comment]
Open a terminal in the folder (or you can [`cd`](https://linuxize.com/post/linux-cd-command/) into it). Assuming you're running `x86_64` architecture (you can use [`lcpu`](https://www.thegeekdiary.com/lscpu-command-examples-in-linux/) to check that), make the binary executable:

```console
$ chmod +x Digital\ Logic\ Sim.x86_64
```

Then run the program:

```console
$ ./Digital\ Logic\ Sim.x86_64
```

**Comment by Bigbfromcle** [comment]
So I tried what _joe773_ said it but this happens, and I'm confused why it can't find the file
![Screenshot 2022-10-09 10 32 38 PM](https://user-images.githubusercontent.com/97521603/194792054-a4a19071-5e0e-4034-978b-23f2bcee2f74.png)
![Screenshot 2022-10-09 10 33 01 PM](https://user-images.githubusercontent.com/97521603/194792059-be8f3174-5eab-4423-bf7d-9f2da91cd721.png)

**Comment by joe733** [comment]
Are you sure you're running the command from the same directory? Try running `ls`, you should see `'Digital Logic Sim.x86_64'`

![image](https://user-images.githubusercontent.com/38415384/194792597-43f92480-6625-48aa-9c3f-4f8a5781d8ff.png)

**Comment by Bigbfromcle** [comment]
Oh I see the issue, the file is still in the folder, I'm going to move files out of the Digital Logic Sim folder and directly into the Linux Folder.

It worked, thank you!
