### ISSUE TITLE
macOS build unable to open

### ISSUE THREAD

**Issue by Devnol** [SebLague/Digital-Logic-Sim#11]
Attempting to launch the built app from itch.io in macOS Big Sur 11.0.1 results in an error "You do not have permission to open this app"

**Comment by SebLague** [comment]
Can you please try downloading it through the itchio app (https://itch.io/app). For some reason that seems to work. Not sure how to fix otherwise.

**Comment by Devnol** [comment]
That's where I got it from

**Comment by Devnol** [comment]
oh the app, sorry

**Comment by Devnol** [comment]
Yep, on the itch.io App it seems to work fine

**Comment by SebLague** [comment]
Great!

**Comment by Devnol** [comment]
Well that doesn't really make the issue resolved as you have a non-functional package on your itch.io and not everyone has the itch.io app.

**Comment by SebLague** [comment]
With latest upload it should now work if you right click to open (instead of double-clicking). Will give a warning, but it can just be ignored. Will reopen the issue though since I agree the solution is not ideal.

**Comment by Devnol** [comment]
Yep, seems to be working now. Thanks!
