### ISSUE TITLE
Cant get this to run on repl.it

### ISSUE THREAD

**Issue by ironswordX-dev** [SebLague/Digital-Logic-Sim#110]
I use an application known as Repl (repl.it) because I use a chromebook. I tried importing this to repl and got this error message: 

> donet run
Couldn't find a project to run. Ensure a project exists in /home/runner/Digital-Logic-Sim, or pass the path to the project using --project

And when I try using --project i get this

>--project
bash: --project: command not found

I tried it in the shell instead of the console and got this

~/Digital-Logic-Sim$ --project
bash: --project: command not found

**Comment by Xanderplayz18** [comment]
I don't think this will be of any use to you now, but I made a web port at https://xanderplayz16.github.io/DLS-GL/
