### ISSUE TITLE
Not available on chromebook

### ISSUE THREAD

**Issue by RickAstley1234** [SebLague/Digital-Logic-Sim#114]
Can you make playable game on the chromebook

**Comment by PKD667** [comment]
chrome os is build on gentoo so the linux version should work if you find a way to acess the core system 
is think there is a tool name crouton that allows you to do that

**Comment by Wayne-sharma** [comment]
> Can you make playable game on the chromebook

yes

**Comment by Xanderplayz18** [comment]
I don't think this will be of any use to you, but https://xanderplayz16.github.io/DLS-GL/ is my port to the web.
