### ISSUE TITLE
[FEATURE REQUEST] Add releases to github

### ISSUE THREAD

**Issue by Oman395** [SebLague/Digital-Logic-Sim#116]
Hey there, just wanted to ask if releases could be added to github-- itch.io works fine for me, but I want to make an AUR entry for this, and I can't find an automated way to download the files from itch. No worries if not, thank you!

**Comment by DoctorMikeReddy** [comment]
My guess is, because it is “Pay what you like“ at itch.io, it won’t come here as a release as this is how donations are made

**Comment by Oman395** [comment]
I decided to brute force it, it's now on the AUR and set up to build w/ unity. It's a long download bc it needs to install unity editor, but oh well
