### ISSUE TITLE
Output flickers when directly connected to true input and a false input

### ISSUE THREAD

**Issue by WaffleDevsAlt** [SebLague/Digital-Logic-Sim#125]
![image](https://user-images.githubusercontent.com/81845843/210463347-d683bbaa-207b-46f3-9f45-a2b57169d3e5.png)
Cant see flicker but just recreate in game...

**Comment by SebLague** [comment]
Hi, this is intended behaviour. If you want to connect multiple signals together directly like this, you'll need to use a tri-state buffer.
