### ISSUE TITLE
Add multiple types of wires

### ISSUE THREAD

**Issue by Suiranoil** [SebLague/Digital-Logic-Sim#13]
When your circuit becomes more complex you need to transfer many bits from one place to another and your board will be full of wires. So wires that can transfer 4bits, 8bits, 16bits and more at once can become very useful and make your project look much better.

**Comment by MrFaul** [comment]
It is true but I'd like to make Alternative suggestion, to group outputs into  a "group output" instead.
To connect both I/O needs to have the same name.
This is much more flexible and faster to implement instead of additional wire types.

**Comment by Broken-Admin** [comment]
To add, I would support the coloring of wires.

**Comment by RobMayer** [comment]
+1 for a 4, 8, 16, and 32 bit bus cable :)

**Comment by dobrosketchkun** [comment]
Nice idea!
