### ISSUE TITLE
Application can't be opened (macOS)

### ISSUE THREAD

**Issue by LostInCompilation** [SebLague/Digital-Logic-Sim#131]
I downloaded the official release (V1.0.2) on the website for macOS. However when I try to open it, I just receive the message "The Application can't be opened". I enabled running uncertified Apps, also right-click-open does not work.

The old version (0.25) works fine on Mac.

Device: M1 Pro MacBook Pro
OS: macOS 13.2

**Comment by Fr3E** [comment]
I found out that you need to enable execute permission inside package i.e.:
`chmod +x "Digital Logic Sim.app/Contents/MacOS/Digital Logic Sim"`

**Comment by LostInCompilation** [comment]
Works now.
Strange I would expect unity to set the flag.

**Comment by alikatgh** [comment]
> I found out that you need to enable execute permission inside package i.e.: `chmod +x "Digital Logic Sim.app/Contents/MacOS/Digital Logic Sim"`

Thanks!
