### ISSUE TITLE
Allow to change size of the circuit

### ISSUE THREAD

**Issue by Suiranoil** [SebLague/Digital-Logic-Sim#14]
Add an ability to change size of the circuit to allow more complex stuff to be made

**Comment by bhargavrpatel** [comment]
Can we do this by grouping pieces and putting them into their dedicated chips?

**Comment by Leonix1** [comment]
> Can we do this by grouping pieces and putting them into their dedicated chips?

We could, yes. But I for example am working on an 8-bit system and at some point the input space just isn't enough for that

**Comment by GamesaltGames** [comment]
I was thinking you could do a sort of ctrl+- or ctrl++ to change the size of the board
