### ISSUE TITLE
My chip is not like the chip in the video

### ISSUE THREAD

**Issue by AtyKlaxas** [SebLague/Digital-Logic-Sim#141]
Hello

I like this project and I follow the videos to the letter
I have a problem with the creation of the 4bit register
the 7 segment is not displayed, not like in the video

How to display the 7 segment on a custom chip?

Kind regards

_The digital display in the video_
![capture video](https://user-images.githubusercontent.com/58552341/216764792-c90d388a-ed48-4206-a15a-40fcce61b84a.PNG)

_The digital display in my case_
_sorry for the non-straight lines_
![capture logiciel](https://user-images.githubusercontent.com/58552341/216766112-f89c7d9e-12ea-4393-bc64-53b58fba7230.PNG)

**Comment by nathan-stewart** [comment]
Feature hasn't been pushed yet.  
https://github.com/SebLague/Digital-Logic-Sim/issues/124

**Comment by ryvexc** [comment]
hold shift buddy, thanks me later

**Comment by AtyKlaxas** [comment]
Thanks !
