### ISSUE TITLE
[feature request] Pull Up and Pull Down resistors?

### ISSUE THREAD

**Issue by AverseMoon** [SebLague/Digital-Logic-Sim#146]
They would be able to be shorted without flickering the wires.

**Comment by AverseMoon** [comment]
I want this so I can make a simple 2-5 wire interface bus.

**Comment by JC3** [comment]
If your intent is to set the default state of unused pins, you could emulate pullup's by using a NOT gate with an unconnected input to output a high. For lows you can just leave them unconnected, or if you want to explicitly show what you're doing you can create a library component consisting of a single output pin and nothing else, and name it "LOW" or something like that.

**Comment by SebLague** [comment]
To connect wires together you'll need to use a tri-state buffer. I don't plan on adding resistors to the simulation, but I'll think about just allowing wired-or in the future.
