### ISSUE TITLE
Better docs

### ISSUE THREAD

**Issue by dbechrd** [SebLague/Digital-Logic-Sim#15]
This application is super cool! Amazing work..

Some things I discovered by watching the video and mashing the keyboard that should be in the README (the "Instructions" screen in-game probably isn't big enough to list every possible command as-is).

- Clicking a chip multiple times will allow you to add that many at the same time.
- Right-click to cancel chip placement.
- Hold Alt key while hovering pins to see their names (why Alt? I feel like hovering should just always display this).

**Comment by Broken-Admin** [comment]
I agree! Possibly submit a PR for a markdown file in the repository as of now?

**Comment by bhargavrpatel** [comment]
> why Alt? I feel like hovering should just always display this
I respectfully disagree. If the pin name is rendered in the position it's currently in, it may get in the way.
