### ISSUE TITLE
Request for Mobile Apps

### ISSUE THREAD

**Issue by SunPodder** [SebLague/Digital-Logic-Sim#150]
Can you export this to Android (and iOS if you wish)? I don't have a pc so I can't build it myself. I tried building this on Github CI, but it have somes bugs on Android.

- Weird keyboard issue.
When naming a new project if I type the key <kbd>a</kbd>, it becomes `aa`. Then again if  type <kbd>b</kbd>, the whole text becomes `aaaabb`.

- Change orientation automatically.
Sticks to portrait mode.

![Screenshot_20230214-172619_Digital Logic Sim](https://user-images.githubusercontent.com/73415680/218724206-9c13cb27-6892-4c55-b759-51c9144e4f1f.jpg)
![Screenshot_20230214-172650_Digital Logic Sim](https://user-images.githubusercontent.com/73415680/218724210-05d0757a-370a-4c22-9b3c-d80f66f41369.jpg)
![Screenshot_20230214-172658_Digital Logic Sim](https://user-images.githubusercontent.com/73415680/218724213-5db1a3c1-cc7c-4bbb-8591-3f443571d7d4.jpg)

This is how the current mobile UI is. Seems good, though I couldn't figure out how to work with it.

**Comment by SebLague** [comment]
Hi, once development is mostly finished I'll consider porting to mobile.
