### ISSUE TITLE
[ISSUE] 7-segment display doesnt show on a created display chip in version 1.0.2 (alpha)

### ISSUE THREAD

**Issue by TheOneTrueMongoloid** [SebLague/Digital-Logic-Sim#153]
In the alpha build 1.0.2 when creating a chip that outputs to a display, the display is absent when using that chip in another chip build.

**Comment by rai68** [comment]
Not implemented yet, see #124

**Comment by TheOneTrueMongoloid** [comment]
Got it. Much appreciated. I'll close this one.
