### ISSUE TITLE
web build

### ISSUE THREAD

**Issue by zcarp7220** [SebLague/Digital-Logic-Sim#166]
would it be possible to put a web build on the itch.io page?

**Comment by BraveCaperCat2** [comment]
No - Unity games are completely in-compatible with browsers - it can only be run on a computer.

**Comment by marcikoHub** [comment]
No, no. If you make special html5 build (which is possible) you can make it run on the web. There's a seperate part of unity for this! Maybe discontinued, but still used!

**Comment by BraveCaperCat2** [comment]
> BraveCaperCat2, you are wrong! If you make special html5 build (which is possible) you can make it run on the web. There's a seperate part of unity for this! Maybe discontinued, but still used!
> 
> Edit: The thing is called Unity WebGL and is still supported by 2021.3.12f1, which is the version of unity of dls!

Well, I'm not good at Unity or C# (but I'm learning) - i just thought unity games only worked on computers or consoles (but this definetly won't run on a console)

**Comment by Xanderplayz16** [comment]
I could compile this for WebGL. I have some spare time on my hands right now.

**Comment by BraveCaperCat2** [comment]
WHOA
________________________________

**Comment by Xanderplayz16** [comment]
The build failed. I am rebuilding.

**Comment by BraveCaperCat2** [comment]
Oh no!
Maybe there are some things that don't work with WEBGL?
________________________________

**Comment by Xanderplayz16** [comment]
It did not fail this time, but I need to add the "Content-Encoding: br" header now.

**Comment by BraveCaperCat2** [comment]
HTTP header or HTML header?
I'm good with web programmming.
________________________________

**Comment by Xanderplayz16** [comment]
HTTP

**Comment by Xanderplayz16** [comment]
I just tested it on github pages, but it will not load.
https://xanderplayz16.github.io/DLS-GL/index.html

**Comment by Xanderplayz16** [comment]
Oh. I missed a file

**Comment by Xanderplayz16** [comment]
Ohh.. I need to rename a folder

**Comment by BraveCaperCat2** [comment]
error in JS console: Failed to load resource: the server responded with a status of 404 ()

This means the server the JS code was trying to reach responded saying that the file could not be found.

I don't have any idea how WebGL compiled unity projects work, but there's the error on the client side
________________________________

**Comment by BraveCaperCat2** [comment]
Ah, I see - that matches with the file not found on client side.

**Comment by BraveCaperCat2** [comment]
BUILD.loader.js seems to be missing - it has a 404 page when i try to access it directly (entering link in web browser, could find from console menu)

**Comment by Xanderplayz16** [comment]
I think I just fixed it.

**Comment by BraveCaperCat2** [comment]
that issue is fixed but a new issue exists:
Unable to parse build/BUILD.framework.js.br! This can happen if build compression was enabled but web server hosting the content was misconfigured to not serve the file with HTTP Response Header "Content-Encoding: br" present. Check browser Console and Devtools Network tab to debug.

________________________________

**Comment by Xanderplayz16** [comment]
I am fixing that right now.

**Comment by Xanderplayz16** [comment]
I think I just fixed it, but I need to test it.

**Comment by BraveCaperCat2** [comment]
same error.
________________________________

**Comment by Xanderplayz16** [comment]
Try hosting it with NGINX but change the Content-Encoding header to br.

**Comment by BraveCaperCat2** [comment]
> Try hosting it with NGINX but change the Content-Encoding header to br.

I'm using the link you posted here: https://xanderplayz16.github.io/DLS-GL/index.html

**Comment by BraveCaperCat2** [comment]
Hmm. there's a syntax error that the console picked up - I have no idea about it even though it's JavaScript since it's compressed.

**Comment by Xanderplayz16** [comment]
I need to go for 1 hour

**Comment by Xanderplayz16** [comment]
I am going to try and build without compression, I hope this works!

**Comment by Xanderplayz16** [comment]
IT WORKS YESSSSS!
![image](https://github.com/SebLague/Digital-Logic-Sim/assets/74632800/189e20de-51c6-4621-9175-138cbba9eed5)

**Comment by Xanderplayz16** [comment]
https://xanderplayz16.github.io/DLS-GL/index.html works now!

**Comment by Xanderplayz16** [comment]
[WebGL Digital Logic Sim.zip](https://github.com/SebLague/Digital-Logic-Sim/files/12062426/WebGL.Digital.Logic.Sim.zip)

**Comment by Xanderplayz16** [comment]
I think I will somehow find a way to compress all of the files into 1 html file.

**Comment by Xanderplayz16** [comment]
IT WORKS!

https://github.com/SebLague/Digital-Logic-Sim/assets/74632800/72fca933-4980-4604-98b9-9608bd84d421

**Comment by loglot** [comment]
> https://xanderplayz16.github.io/DLS-GL/index.html works now!

sadly it doesn't save

**Comment by Xanderplayz18** [comment]
It does save, you just need to exit to the main menu to save

**Comment by zcarp7220** [comment]
Thank you for all this.

**Comment by marcikoHub** [comment]
Xander, can you update it? It just shows an error. 

404
There isn't a GitHub Pages site here.
If you're trying to publish one, read the full documentation to learn how to set up GitHub Pages for your repository, organization, or user account.

**Comment by xandaaah** [comment]
I changed my username. https://xandaaah.github.io/DLS-GL/index.html

**Comment by loglot** [comment]
> I changed my username. https://xandaaah.github.io/DLS-GL/index.html

Damn, I thought I said something about this, ig I forgot though

**Comment by marcikoHub** [comment]
It still errors out. Server not found.

**Comment by loglot** [comment]
I forked the repo, this link works for me
[https://log-lot.github.io/DLS-GL/](https://log-lot.github.io/DLS-GL/)

**Comment by marcikoHub** [comment]
Woks for me as well. Thanks.

wt., 11 lut 2025, 16:13 użytkownik loglot ***@***.***>
napisał:

**Comment by marcikoHub** [comment]
Can someone make a version for 2.0? The current one is for 1.0. Thanks
