### ISSUE TITLE
Chip doesn't update?

### ISSUE THREAD

**Issue by skiller8641** [SebLague/Digital-Logic-Sim#168]
i have a messy chip that is supposed to convert a binary number (only 1 and 2 for now) in a way to be able to connect it to the 7 segment diplay, but the signal just stop in one chip, idk know why, the first time, before i saved it, it worked but not anymore, does anyone know why?
![Capture d’écran 2023-03-23 191240](https://user-images.githubusercontent.com/94241636/227309229-c56db79b-4197-4bfc-89b2-e47aa731eaf5.png)
![Capture d'écran 2023-03-23 191426](https://user-images.githubusercontent.com/94241636/227309235-39509c09-d6d7-4a1e-bd40-c740868ce6bd.png)

**Comment by skiller8641** [comment]
I fixed it, i needed to restart the project, if you have the same thing, save everything even if there is no signal going out of a chip that should be outputting one, go to the menu and re open the project, fixed

**Comment by skiller8641** [comment]
it also may be because there is to much happening, idk

**Comment by Highlandword9** [comment]
@skiller8641 
issue solved? >> close issue?

**Comment by skiller8641** [comment]
i guess

**Comment by skiller8641** [comment]
i guess
