### ISSUE TITLE
Output node broken and flashing

### ISSUE THREAD

**Issue by Headshot56** [SebLague/Digital-Logic-Sim#171]
I tried to setup a simple or gate after updating to the newest version but when I connect more than one line to output it will flash extremely fast when it is supposed to hold unless both wires are on. This obviously breaks or gates making it impossible to use.
https://drive.google.com/file/d/1PteQT23b2yT4uSVg1Rr6-SvVDFPSdEOV/view?usp=sharing

**Comment by milochristiansen** [comment]
That is intended behavior.

You do not make an OR gate by connecting two wires to a pin. For example, one possible way to make an OR gate is `NOT A NAND NOT B`, where `NAND` is `NOT (A AND B)`.

**Comment by Headshot56** [comment]
What about the hyper speed?

**Comment by milochristiansen** [comment]
The fast flashing is how the sim indicates that a wire has an "indeterminate" or invalid state.
