### ISSUE TITLE
Incompatible with the 2nd video

### ISSUE THREAD

**Issue by simon-tiger** [SebLague/Digital-Logic-Sim#18]
Sequential logic seems not to be working (that's the kind of circuit the loops back on itself) 🙁

**Comment by SebLague** [comment]
Could you post a screenshot of the setup you have that isn't working? I tested a few sequential setups with the latest build and it seems to be working fine to me.

**Comment by simon-tiger** [comment]
The simplest sequential logic circuit you mentioned in the video (the SR Latch) seems not to be working:
<img width="958" alt="Screenshot 2020-12-05 at 13 09 39" src="https://user-images.githubusercontent.com/21979673/101242697-53780d80-36fb-11eb-8701-063089bd6c55.png">

**Comment by simon-tiger** [comment]
Just looking at the inputs/outputs seems fine, but the NOR gate outputs are wrong.

**Comment by simon-tiger** [comment]
(Wait...maybe I just implemented the NOR gates themselves wrong?)

**Comment by SebLague** [comment]
Certainly seems like the NOR gates are misbehaving. Easiest implementation of NOR gate in this sim would be to invert both inputs and feed that into an AND gate. Could you try it again? Alternatively, you could send me your save data and I could take a look.
On mac that should be in: ~/Library/Application Support/Sebastian Lague/Digital Logic Sim)
Or on windows: C:\Users\<userprofile>\AppData\LocalLow\Sebastian Lague\Digital Logic Sim

**Comment by Leonix1** [comment]
They work fine for me (Windows 10 64-bit)

**Comment by simon-tiger** [comment]
Anyway, I tried it with building the NOR gates correctly, and it seems to work, so yeah...
