### ISSUE TITLE
RAM doesn't save state

### ISSUE THREAD

**Issue by DaniLucky06** [SebLague/Digital-Logic-Sim#187]
i have built some 16 Byte RAM components, and have tried to create some components that use ram to save microinstructions for each instruction (store REGA to address = READ next cell + store to reg c > READ next next cell + store reg C to RAM with that address), and when i've tried saving the chips, all the data inside their RAM gets deleted, rendering it useless.
Is it a bug of my game, is there something i can do to fix it, or not?

**Comment by thewindboi** [comment]
It is not a bug; RAM in real life does not actually save state, so why should it here?

**Comment by mahdoosh1** [comment]
You idiot when have you seen a ram to keep state while unpowered?

**Comment by DaniLucky06** [comment]
> You idiot when have you seen a ram to keep state while unpowered?

Thank you very much, kind person, to answer me by insult 6 months after i asked the question, and after it had already been answered.

**Comment by mahdoosh1** [comment]
> > You idiot, when have you seen a ram keep state while unpowered?
> 
> Thank you very much, kind person, for answering me by insult six months after I asked the question and after it had already been answered.

Youre welcome, and i apologize for calling you stupid.

**Comment by Highlandword9** [comment]
@DaniLucky06 
issue solved?  >>  close issue?
