### ISSUE TITLE
No decimal number in output group shown

### ISSUE THREAD

**Issue by dertroglodyt** [SebLague/Digital-Logic-Sim#19]
Windows 10, 4k Display in window mode.

![grafik](https://user-images.githubusercontent.com/565621/101224488-09f1d900-368f-11eb-8513-628ae04651c9.png)

P.S.: Thanks for this marvelous series and tool.

**Comment by SebLague** [comment]
Thanks for the report, fixed in the latest version

**Comment by dertroglodyt** [comment]
Works like a charme. Thanks.
