### ISSUE TITLE
Disabled Fullscreen Can't Change it Back

### ISSUE THREAD

**Issue by CommanderGL** [SebLague/Digital-Logic-Sim#200]
I disabled fullscreen can't but change it back because now apply button is under my taskbar on Ubuntu.

**Comment by Highlandword9** [comment]
can you add a screenshot?

**Comment by CommanderGL** [comment]
Here, look at the bottom. I even tried redownloading, but nothing works. I can't find where it's stored.
![Screenshot from 2023-11-14 08-19-46](https://github.com/SebLague/Digital-Logic-Sim/assets/85912189/f58c7cb1-0952-424f-bc07-3f0a72c3abf3)

**Comment by CommanderGL** [comment]
Oh ya that works thank you.
