### ISSUE TITLE
Multiple inputs

### ISSUE THREAD

**Issue by MikZero0** [SebLague/Digital-Logic-Sim#204]
Encountered a problem while making a program counter using T flip-flops.
When I tried connecting the outputs of the and gates to the inputs of the flip-flops, the counter went crazy. The only solution is to add or gates at the inputs.
The issue starts when there is a big number of possible inputs and I have to make custom OR gates for every input on the flip-flops.

setup:
![image](https://github.com/SebLague/Digital-Logic-Sim/assets/153509164/c62761ef-ea60-4568-9941-11330932fb7f)

Just look at what I did to my RAM chip after i found out.
![image](https://github.com/SebLague/Digital-Logic-Sim/assets/153509164/6834a263-a8fd-42ed-b40c-341f723ff364)

What I want in the next update is to be able to wire up as many outputs to one input, and for the program to automatically OR them.

</div>

**Comment by Xanderplayz18** [comment]
It is because there is a conflict, on and off signals are in the same cable, and the game goes crazy.
