### ISSUE TITLE
Could you please add a setting to adjust the speed of the electricity going through the wires like in the most recent video?

### ISSUE THREAD

**Issue by CalebArbeau** [SebLague/Digital-Logic-Sim#21]

**Comment by Broken-Admin** [comment]
Could this be done via allowing the user to step the gamestate?

**Comment by janispritzkau** [comment]
I don't think it has been implemented yet. It looks like the simulation happens instantly until it finds a cycle.

**Comment by Leonix1** [comment]
Yes, but it has to have been implemented somewhat, since it appears in Lague's new video and honestly I doubt he animated that thing

**Comment by dkapur17** [comment]
Have there been any updates regarding this? Thanks.
