### ISSUE TITLE
Compilation of multiple issues.

### ISSUE THREAD

**Issue by Broken-Admin** [SebLague/Digital-Logic-Sim#22]
I have encountered a few issues with the system and felt I'd compile them together, focusing on the save-file issies.

- Files are saved as `txt` instead of `json` despite containing JSON objects.
- Per #15, more documentation would be beneficial. Specifically where the specifically files are saved, a link to where files are saved can be found [here](https://stackoverflow.com/a/44421935).This could also aid in reducing confusion noted in #16.
- Lastly, I feel it would be beneficial to the functioning of the repository to provide an issue format.

**Comment by bhargavrpatel** [comment]
@Broken-Admin Addressed some of your comments in https://github.com/SebLague/Digital-Logic-Sim/pull/25
