### ISSUE TITLE
Somethings seems to be broken when u use clock generator

### ISSUE THREAD

**Issue by LionariusPy** [SebLague/Digital-Logic-Sim#23]
So i created a circuit that calculates first 9 numbers of Fibonacci sequence. When i manually switch on and off clock signal everything works fine, but when i use "NOT clock" to automatically switch clock signal algorithm seems to be broken.

NOT clock:
![image](https://user-images.githubusercontent.com/45388086/101239304-891af780-36f7-11eb-9473-0bc78a953864.png)

If you switch clock by hand algorithm goes through 1, 1, 2, 3, 5, 8, 13, 21 and then some random numbers and comes back to 1; but with NOT clock it goes through 1, 1, 2, 3, 4, 5, 6, 8, 9

video: https://youtu.be/q1MB8FMnUlU

**Comment by willcatmeow** [comment]
was this ever answered?

**Comment by Leonix1** [comment]
> was this ever answered?

Nope, but I would guess that has to do with the Clock Speed. The Clock would probably have to be slower for the calculation to work
