### ISSUE TITLE
Cant figure out how to use decimal display on input and output pins

### ISSUE THREAD

**Issue by Fargekritt** [SebLague/Digital-Logic-Sim#26]
Checked version, looked for other issues with the same but can find anything

**Comment by KristanSmout** [comment]
To show the decimal display use the + and - keys to add multiple inputs or outputs at the same time and it appears

**Comment by FelixSelter** [comment]
> To show the decimal display use the + and - keys to add multiple inputs or outputs at the same time and it appears

Do you know how to create negative decimal?

**Comment by QuietRocket** [comment]
> Do you know how to create negative decimal?

If you enable the "signed" checkbox on the input/output group, it would understand the binary value as a [two's complement number](https://en.wikipedia.org/wiki/Two%27s_complement).

**Comment by FelixSelter** [comment]
> > Do you know how to create negative decimal?
> 
> If you enable the "signed" checkbox on the input/output group, it would understand the binary value as a [two's complement number](https://en.wikipedia.org/wiki/Two%27s_complement).

Sorry but could you might add some images or detailed instructions. I cant find any checkbox

**Comment by QuietRocket** [comment]
> Sorry but could you might add some images or detailed instructions. I cant find any checkbox

@FelixSelter 


https://user-images.githubusercontent.com/56984521/102735310-e9648880-42f6-11eb-8f6f-ac2671def7cd.mov

**Comment by FelixSelter** [comment]
> 
> 
> > Sorry but could you might add some images or detailed instructions. I cant find any checkbox
> 
> @FelixSelter
> Signed.Decimals.mov
> 
> When the signed checkbox is enabled, the top pin represents -(2^4) = -16 and the bottom one is 2^0 = 1. -16 + 1 = -15.

Thanks a lot. It seems like I had to update my version

**Comment by Ciskizie** [comment]
> To show the decimal display use the + and - keys to add multiple inputs or outputs at the same time and it appears

the  + and - keys dont work for me?

**Comment by Oman395** [comment]
Yeah, it's a feature that was removed

**Comment by FelixSelter** [comment]
It was removed in the recent reweite but will be added back

**Comment by Rnghjikl** [comment]
> > Sorry but could you might add some images or detailed instructions. I cant find any checkbox
> 
> @FelixSelter
> 
>  Signed.Decimals.mov 
> When the signed checkbox is enabled, the top pin represents -(2^4) = -16 and the bottom one is 2^0 = 1. -16 + 1 = -15.

Huh? I don't see this checkbox anywhere, where did it go???
