### ISSUE TITLE
Labels on I/O

### ISSUE THREAD

**Issue by MahdiyarTH** [SebLague/Digital-Logic-Sim#27]
Hey, how can we have label on I/O like this pic?
![image](https://user-images.githubusercontent.com/25479661/101258800-2c8cfc00-373a-11eb-803a-867a03f7bac8.png)

and how can we convert binary to decimal like this?
![image](https://user-images.githubusercontent.com/25479661/101258836-62ca7b80-373a-11eb-8896-92ee7f6bb247.png)

**Comment by 29-29** [comment]
about the decimal to binary, it is already mentioned in #26 .

and as for the labels, if you hold ALT while hovering over the pin, you can see the pins' label, that is if you set a label for it. that's as much as we can get as of v0.24

**Comment by SebLague** [comment]
Pin display options are now available from the options menu on the top bar (next to create) in v0.25
