### ISSUE TITLE
Compilation?

### ISSUE THREAD

**Issue by ichbineinNerd** [SebLague/Digital-Logic-Sim#28]
hey, could you add a section in the readme on how to compile this project? neither the readme, nor the itchio (including the comments ive seen) mention anything, so I must be missing something obvious - there does not seem to be a compile script, makefile, C# solution, or anything of that nature though

**Comment by wrutkowski** [comment]
You should use Unity to open this project.

**Comment by SebLague** [comment]
If you want to modify the project, you'll need to download the Unity editor (from unity3d.com). If you're just looking to play, then download the executable from itch.io and run it (no compilation necessary).
