### ISSUE TITLE
I/O bars on the side of the screen not displayed while Fullscreen on Macbook Air

### ISSUE THREAD

**Issue by takoyaro** [SebLague/Digital-Logic-Sim#3]
When using the app in Fullscreen, the bars on both sides of the screen to add I/Os are not visible.
Leaving Fullscreen mode is the only way to see it.

Native Resolution: 1440x900

**Comment by Leonix1** [comment]
This also occurs at 1680x1050 with Windows 10

**Comment by SebLague** [comment]
Should now be visible in the latest version
