### ISSUE TITLE
Error opening the project

### ISSUE THREAD

**Issue by Samuel-Fortunato** [SebLague/Digital-Logic-Sim#31]
Hello!
I am new to github so sorry in advance if im doing something wrong.
As I said I am new to github (it's my first time using it) and also to unity (already watched some tutorials but never made a complete game), but im trying to see/edit the unity project.
So i went to the project/repository (i dont know whats the correct word) and clicked the code button and then download ZIP. Then on unity hub, I added a new project, selecting the extracted folder.
When I opened the project in unity editor there was only an empty 3D scene and several error messages appeared:

![image](https://user-images.githubusercontent.com/50797513/101293832-e99b5900-380b-11eb-97c3-fb688b18f7f2.png)

I am using the latest unity version: 2019.4.15.f1.
Please tell me if im doing something wrong, and sorry if this is not the right place to ask for help.
Thanks in advance :)

**Comment by SebLague** [comment]
Hmm those just look like some GUI errors, should be fine to ignore them (or you can clear them with that button on the middle left. Currently you're in an empty default scene, so go to the project tab (just above that clear button) and navigate to the scenes folder. From there you can open either the menu or the chip design scene.
