### ISSUE TITLE
Buffer-like Delay using isCyclic not persisting into saved component

### ISSUE THREAD

**Issue by RobMayer** [SebLague/Digital-Logic-Sim#34]
This was a bit of a hack in order to get a Buffer-like component, but I essentially took an AND gate, wired both A and B inputs into single SIGNAL IN. I then went into the text file and enabled "isCyclic" intentionally. The end result is a Buffer where the output will power on one "tick" after the input is powered on. This works great for a clock assembly, like so:

![image](https://user-images.githubusercontent.com/5171361/101715782-0f259e00-3a6a-11eb-962c-368fa2a55883.png)

However, when I use this to create a component, the logic for the delay is gone and the clock never oscillates. I can provide my save file if need be.

**Comment by RobMayer** [comment]
the "Buffer" component, illustrating the forced "isCyclic" flag

`{
    "name": "BUF",
    "creationIndex": 6,
    "colour": {
        "r": 0.7641509771347046,
        "g": 0.40998053550720217,
        "b": 0.19103774428367616,
        "a": 1.0
    },
    "nameColour": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0,
        "a": 1.0
    },
    "componentNameList": [
        "SIGNAL IN",
        "SIGNAL OUT",
        "AND"
    ],
    "savedComponentChips": [
        {
            "chipName": "SIGNAL IN",
            "posX": -7.6431,
            "posY": 0.67,
            "inputPins": [],
            "outputPinNames": [
                "IN"
            ]
        },
        {
            "chipName": "SIGNAL OUT",
            "posX": 7.6431,
            "posY": 0.757,
            "inputPins": [
                {
                    "name": "OUT",
                    "parentChipIndex": 2,
                    "parentChipOutputIndex": 0,
                    "isCylic": true
                }
            ],
            "outputPinNames": []
        },
        {
            "chipName": "AND",
            "posX": -2.5327,
            "posY": 0.6177,
            "inputPins": [
                {
                    "name": "A",
                    "parentChipIndex": 0,
                    "parentChipOutputIndex": 0,
                    "isCylic": false
                },
                {
                    "name": "B",
                    "parentChipIndex": 0,
                    "parentChipOutputIndex": 0,
                    "isCylic": true
                }
            ],
            "outputPinNames": [
                "OUT"
            ]
        }
    ]
}`

**Comment by RobMayer** [comment]
An interesting side-effect of this BUF object.

![image](https://user-images.githubusercontent.com/5171361/101724652-186c3600-3a7d-11eb-933e-b6d560411ad9.png)

This output will be delayed by 4 "ticks" from the input.

**Comment by CursedFlames** [comment]
A similar, simpler case: a NOT connected to itself and the output functions as a clock, but when used as a component it doesn't output anything.

**Comment by RobMayer** [comment]
I think I figured out why. the "flow" of a powering on propagates each tick, but the cutting of power is immediate. in other words your clock has the power pulled before it's power can reach anything.

**Comment by RobMayer** [comment]
cutting the clock speed in half seems to work better as a clock because of the delayed-on but instant-off issue.

![image](https://user-images.githubusercontent.com/5171361/101787759-6f016080-3acd-11eb-8a04-ce8afb015b17.png)

**Comment by RobMayer** [comment]
Even more fun with this little hacked component: a rising and falling edge detector:
RISING goes high for one tick when IN goes high
FALLING stays high except for one tick when IN goes low

![image](https://user-images.githubusercontent.com/5171361/101804018-23f04900-3adf-11eb-9f30-76e2660260d8.png)
