### ISSUE TITLE
Very slow performance on macOS (Big Sur)

### ISSUE THREAD

**Issue by ryan-saffer** [SebLague/Digital-Logic-Sim#35]
I am running macOS big sur (11.0.1) and the application runs extremely slowly, and even slows down the rest of my computer to the point where it became difficult to force quit the application.

Anyone else getting this behaviour?

**Comment by MarsKittenPro** [comment]
i get it really slow on catalina too.
82% cpu usage

**Comment by AOx0** [comment]
Same problem. I think there should be a button to run or not the simulation. Maybe that infinite loop of simulating is the cause. 

macOS Big Sur (11.2.2)
