### ISSUE TITLE
Suggestion: output options

### ISSUE THREAD

**Issue by Andrupka** [SebLague/Digital-Logic-Sim#37]
Hi! I am a fan of your channel and I like your simulation tool, but this would be better if you would add something like 7-segment displays so you would be able to convert 4-bit binary input to usual numbers. I know that it would be difficult, but it would be cool

**Comment by QuietRocket** [comment]
#26 mentions how to display binary numbers as decimal numbers, as it is shown in the videos. It's an undocumented gem.

**Comment by Andrupka** [comment]
Thanks!

**Comment by 0sy-is-ssucch-a-s-st-puid-idio-t-l-l-l** [comment]
@Andrupka a Ŧƙ𝔫 πᘜ𝖆!
