### ISSUE TITLE
Instructions menu does not display properly on 21:9

### ISSUE THREAD

**Issue by TobiasDeBruijn** [SebLague/Digital-Logic-Sim#38]
Screenshot should explain it:
![image](https://user-images.githubusercontent.com/28569170/102343601-0b7aa580-3f9b-11eb-83a2-15edfce744b9.png)

Environment:
Display resolution: 2560x1080 (21:9)
OS: Windows 10 Home, v. 1909
GPU: RTX 2080Ti
Game version: (no version is shown anywhere, date: 16/12/2020 (dd/mm/YYYY)

**Comment by TheDutchMC** [comment]
After going into settings, and setting the resolution to 1920x1080 it does show properly, though 21:9 support would be awesome :)
