### ISSUE TITLE
add V-Sync option

### ISSUE THREAD

**Issue by Zycrasion** [SebLague/Digital-Logic-Sim#39]
on mac without it its becoming very laggy.
i think that this would optimise it alot.

**Comment by Turnip1234** [comment]
V-Sync just *limits* the framerate, right?

**Comment by Turnip1234** [comment]
how would that make it less laggy?

**Comment by AuracleTech** [comment]
Exactly my issue, the framerate seems to not be limited and due to the GPU shortage my PC and me are crying right now
