### ISSUE TITLE
A timer input!

### ISSUE THREAD

**Issue by eteran** [SebLague/Digital-Logic-Sim#46]
Would be awesome if an input could be set to be a timer. that could be tied to a play/stop button at the top. When "running", it would continuously toggle on and off at a constant rate. Even better if I get to pick the rate ;-)

**Comment by QuietRocket** [comment]
A clock pulse with enable switch can be implemented using elementary gates. If you want an to specify a delay however, you will either need to implement a counter, use buffers, or have it implemented at the application level.

https://user-images.githubusercontent.com/56984521/103047329-fb853780-453f-11eb-885e-722475c93697.mov

**Comment by eteran** [comment]
That's pretty awesome! Though I do think there is still some benefit to it being "built in" to the simulation IMO.

This is good enough for now though 🙂

**Comment by Rilazy** [comment]
This actually doesn't work in the program. While it should work, and does in the chip editor, once you save the oscillating chip and place it to use in another circuit, it will simply output nothing.
