### ISSUE TITLE
Linux build unable to open

### ISSUE THREAD

**Issue by willcatmeow** [SebLague/Digital-Logic-Sim#55]
When I downloaded the program and ran the executable on ubuntu the program opens for around half a second and then just closes, I don't know anything else about the problem, might update later after trying it again.

**Comment by dromer** [comment]
Which DSL version?
Which Ubuntu version?

0.25 works perfectly on Debian Buster for me

**Comment by willcatmeow** [comment]
ubuntu 20.10, and i'll check the dsl version later today

**Comment by willcatmeow** [comment]
Ok, although i deleted the copy of dsl, it's 0.25 , the latest version

**Comment by willcatmeow** [comment]
I tried again just in case but no luck

**Comment by dromer** [comment]
How are you running the executable? Try running it from a terminal and see if there is any standard output there.

**Comment by willcatmeow** [comment]
I'm running the executable normally after unzipping the .zip I think, tomorrow if I have time I'll try it and see if it works.

**Comment by willcatmeow** [comment]
> I'm running the executable normally after unzipping the .zip I think, tomorrow if I have time I'll try it and see if it works.

idk how to run from terminal

**Comment by dromer** [comment]
easiest is if you know basic terminal navigation
```
~$ cd <path_to_download_dir>
~$ unzip -x Digital\ Logic\ Sim\ \(linux\).zip
~$ cd Digital\ Logic\ Sim\ \(linux\)/
~$ ./Digital\ Logic\ Sim.x86_64
```

**Comment by willcatmeow** [comment]
yes, now i do, and getting to dls wasn't a problem, it was the last command as i didn't know how to open the executable.

**Comment by willcatmeow** [comment]
when i opened it from terminal it had the same result

**Comment by willcatmeow** [comment]
i wait...

**Comment by Leonix1** [comment]
I couldn't reproduce this either, sorry. I am using a VM though...

**Comment by willcatmeow** [comment]
maybe it's my hardware

________________________________

**Comment by Leonix1** [comment]
Maybe. You could try it with a VM yourself, perhaps that helps

**Comment by willcatmeow** [comment]
well, i would, but minecraft barely runs on this thing
________________________________

**Comment by willcatmeow** [comment]
let alone a vm
________________________________

**Comment by Leonix1** [comment]
Maybe your hardware **is** the problem then. Are you running 32 or 64 bits?

**Comment by Leonix1** [comment]
Or 8 perhaps

**Comment by willcatmeow** [comment]
64 bit ubuntu with windows installed too
________________________________

**Comment by willcatmeow** [comment]
64 bit windows 10
________________________________

**Comment by Leonix1** [comment]
Tried on windows?

**Comment by willcatmeow** [comment]
no, but i mainly use linux
________________________________

**Comment by Leonix1** [comment]
Maybe it works on Windows. Would be nice

**Comment by 4321ba** [comment]
Ubuntu 20.04 here, seems to run just fine for me.

**Comment by willcatmeow** [comment]
i'm on 20.10
________________________________

**Comment by Tigralt** [comment]
Run fine on Ubuntu PopOS 20.04 as well. maybe a library problem ?

**Comment by willcatmeow** [comment]
Ubuntu PopOS?? those are different Linux distros
________________________________

**Comment by cool146** [comment]
i cant open it to im on linux endless
