### ISSUE TITLE
How to add so that the inuts show decimal numbers as in the video

### ISSUE THREAD

**Issue by traliotube** [SebLague/Digital-Logic-Sim#60]
How to add so that the inuts show decimal numbers as in the video
https://youtu.be/QZwneRb-zqA?list=WL&t=664
![image](https://user-images.githubusercontent.com/69894187/109608353-c3a5fc00-7b4f-11eb-9470-0938c3544438.png)

**Comment by Lanidae** [comment]
When you're hovering over the left or right sides to create an input/output, press the + key on your keyboard and it'll create a group that you can do that with.

**Comment by Leonix1** [comment]
[https://github.com/SebLague/Digital-Logic-Sim/issues/27](https://github.com/SebLague/Digital-Logic-Sim/issues/27)

**Comment by traliotube** [comment]
> When you're hovering over the left or right sides to create an input/output, press the + key on your keyboard and it'll create a group that you can do that with.

Thanks a loooooooot
