### ISSUE TITLE
Is project saved when testing scene?

### ISSUE THREAD

**Issue by Audionysos** [SebLague/Digital-Logic-Sim#61]
Hello, I have a silly question. I'm not really experienced with unity and just opened the project to mess around after watching the video. I've created a 4-register (16 bits of storage) addressable memory module and just don't have a heart to throw it away after all that wiring... :P I don't know if the project will be available after stopping debugging? I would like to play with it in the future.

**Comment by Turnip1234** [comment]
No sadly :c it doesn't save

**Comment by Leonix1** [comment]
Not even if you press the literal save button? o.0

**Comment by Audionysos** [comment]
> s

**Comment by Audionysos** [comment]
> Not even if you press the literal save button? o.0

Where is a "save" button?

**Comment by Audionysos** [comment]
I mean I'm in "play mode", like this
![unity_play_mode](https://user-images.githubusercontent.com/26059765/109979506-428d6700-7cff-11eb-8162-aad389066ff7.jpg)

Also I'm not sure If I can't just figure it out or already created modules are not editable?

**Comment by Turnip1234** [comment]
Sadly there's no way to save that, because you didn't create a project so its not writing to anywhere on your disk. There is _currently_ no way to edit chips, however there is a pull request for an "edit menu" that allows you to rename and delete chips. So if _you_ want to program an edit menu, feel free to, I'm sure others would benefit from it, but sadly there is no way to edit chips currently.

**Comment by Turnip1234** [comment]
by " if you want to program an edit menu" I mean "if you want to add the ability to edit chips"

**Comment by Audionysos** [comment]
> Sadly there's no way to save that, because you didn't create a project so its not writing to anywhere on your disk. There is _currently_ no way to edit chips, however there is a pull request for an "edit menu" that allows you to rename and delete chips. So if _you_ want to program an edit menu, feel free to, I'm sure others would benefit from it, but sadly there is no way to edit chips currently.

Fortunately I did started it from "menu" scene and create a project and it's saved :D 
Thanks
