### ISSUE TITLE
Loading/Saving Circuits (Enhancement)

### ISSUE THREAD

**Issue by Zeyu-Li** [SebLague/Digital-Logic-Sim#63]
Not sure if anyone has a fork with this yet but it would be great if you could load circuits from a json file and also save the circuits from a json file

**Comment by Zeyu-Li** [comment]
Looks like it's already stored in a JSON format @ %userprofile%\AppData\LocalLow\Sebastian Lague\Digital Logic Sim\SaveData so it shouldn't be too hard to load JSON->read->store to LocalLow

**Comment by okyloky9** [comment]
I'm not the best with C# or Unity, but when I attempted that I ran into a couple of issues:
- The slider handles that spawn when you create inputs didn't get created, so you couldn't move around/rename the inputs
- The inputs didn't work at all (on/off) nor did any of the wires or other logic gates connected to them
I believe there's more to it than just creating the chip items based off the JSON, there must be more functions I'm missing in the code.

**Comment by okyloky9** [comment]
https://github.com/Tigralt/Digital-Logic-Sim   this person has created a working view. You can download the source code here and run it in unity, there's no build for it yet.

There's also #66 which adds all the other modifications people have made, including the one I just posted

**Comment by AOx0** [comment]
Builds for #66 version are available here:

- [macOS (Intel)](https://github.com/AOx0/Digital-Logic-Sim--Unofficial/releases/download/v0.32/DLS_v0.32_Intel_macOS.zip)
- [Windows (x86)](https://github.com/AOx0/Digital-Logic-Sim--Unofficial/releases/download/v0.32/DLS_v0.32_x86_Windows.zip)
- [Windows (x86_64)](https://github.com/AOx0/Digital-Logic-Sim--Unofficial/releases/download/v0.32/DLS_v0.32_x86_64_Windows.zip)
- [Linux (x86_64)](https://github.com/AOx0/Digital-Logic-Sim--Unofficial/releases/download/v0.32/DLS_v0.32_x86_64_Linux.zip)

As @okyloky9 said it includes working import/export.
