### ISSUE TITLE
Circuit fails if compiled

### ISSUE THREAD

**Issue by RadiantUwU** [SebLague/Digital-Logic-Sim#65]
The clock is a NOT gate, connected to the pause pin and self wired xor, that self wired xor is connected to an and gate, which is connected to EN and OUT
RS latch is an RS LATCH type NOR 
circuit: 
![image](https://user-images.githubusercontent.com/69520693/113895057-42d2c380-97d1-11eb-81b5-bf4a58d5d4e5.png)

**Comment by RadiantUwU** [comment]
The circuit above is a 1 tick pulser

**Comment by jf0772256** [comment]
ran into this myself when building a clock/timer circuit. when in the circuit it works, but when I created the chip package, the pulse output refuses to output...

**Comment by technikhea** [comment]
me too tried 10 times with other names
