### ISSUE TITLE
iOS/web app

### ISSUE THREAD

**Issue by dullbananas** [SebLague/Digital-Logic-Sim#71]

**Comment by Turnip1234** [comment]
I compiled and hosted a web app, giving credit to Sebastian Lague, and all of the contributors:
[https://geekveggie.dev/UnityGames/Digital Logic Sim/index](https://geekveggie.dev/UnityGames/Digital%20Logic%20Sim/index)

**Comment by Turnip1234** [comment]
Without an Apple Developer license, which costs 99 USD a year there is no way to make an IOS version.

**Comment by dullbananas** [comment]
thank you. there's some issues (safari on ipados 14.5.1):

* i can't export circuits to save somewhere else

* import button does nothing

* touching the "keyboard" element causes crash

issues seem to be disabled on the repo

**Comment by dullbananas** [comment]
also,wire creation can't be exited on touch screen

**Comment by Turnip1234** [comment]
The import/export buttons do not work in my app version, either. I have no idea why. The keyboard crash does not happen in the app, I might take some time to debug later. Remember, this app is designed for computer, so some things may not work properly on iPad (such as wire creation). EEPROM also does not work, because of the way it interacts with the file system.

I may take some time to debug these things in the future, but Digital Logic Sim was never really meant to run in a web browser, so some things may not be possible.

**Comment by dullbananas** [comment]
oh and here's the error when touching the keyboard

```
An error occurred running the Unity content on this page. See your browser JavaScript console for more info. The error was:
abort("To use dlopen, you need to use Emscripten's linking support, see https://github.com/kripken/emscripten/wiki/Linking") at jsStackTrace@https://geekveggie.dev/UnityGames/Digital%20Logic%20Sim/Build/WebGL.framework.js:2:16343
stackTrace@https://geekveggie.dev/UnityGames/Digital%20Logic%20Sim/Build/WebGL.framework.js:2:16517
abort@https://geekveggie.dev/UnityGames/Digital%20Logic%20Sim/Build/WebGL.framework.js:2:758
_dlopen@https://geekveggie.dev/UnityGames/Digital%20Logic%20Sim/Build/WebGL.framework.js:2:173717
wasm-stub@[wasm code]
<?>.wasm-function[60592]@[wasm code]
<?>.wasm-function[60590]@[wasm code]
<?>.wasm-function[62084]@[wasm code]
<?>.wasm-function[39542]@[wasm code]
<?>.wasm-function[39539]@[wasm code]
<?>.wasm-function[39538]@[wasm code]
<?>.wasm-function[39537]@[wasm code]
<?>.wasm-function[29947]@[wasm code]
<?>.wasm-function[23440]@[wasm code]
<?>.wasm-function[63220]@[wasm code]
wasm-stub@[native code]
https://geekveggie.dev/UnityGames/Digital%20Logic%20Sim/Build/WebGL.framework.js:2:479045
invoke_iiiii@https://geekveggie.dev/UnityGames/Digital%20Logic%20Sim/Build/WebGL.framework.js:2:345773
<?>.wasm-function[63220]@[wasm code]
<?>.wasm-function[61248]@[wasm code]
<?>.wasm-function[60539]@[wasm code]
<?>.wasm-function[4167]@[wasm code]
<?>.wasm-function[4165]@[wasm code]
<?>.wasm-function[10108]@[wasm code]
<?>.wasm-function[10106]@[wasm code]
<?>.wasm-function[10164]@[wasm code]
<?>.wasm-function[10146]@[wasm code]
<?>.wasm-function[7757]@[wasm code]
<?>.wasm-function[10130]@[wasm code]
<?>.wasm-function[4474]@[wasm code]
<?>.wasm-function[12685]@[wasm code]
<?>.wasm-function[12887]@[wasm code]
<?>.wasm-function[13499]@[wasm code]
<?>.wasm-function[40541]@[wasm code]
<?>.wasm-function[40540]@[wasm code]
<?>.wasm-function[39760]@[wasm code]
<?>.wasm-function[39759]@[wasm code]
<?>.wasm-function[29780]@[wasm code]
<?>.wasm-f
```

**Comment by Turnip1234** [comment]
Yeah same thing happens on Windows10 with Brave, so I don't think it's a safari/iPad specific thing

**Comment by Xanderplayz18** [comment]
The link is now down, so use https://xanderplayz16.github.io/DLS-GL/ which is my port.
