### ISSUE TITLE
Closes immediatly after opening

### ISSUE THREAD

**Issue by angel-carvajal-coder** [SebLague/Digital-Logic-Sim#72]
The simulation just doesn't work. I have ran the Windows version before on the same computer, so the problem is probably the Linux compilation.

**Comment by Turnip1234** [comment]
What device are you running it on

**Comment by Turnip1234** [comment]
You can always use the [web version](https://geekveggie.dev/UnityGames/Digital%20Logic%20Sim/index.html) that I compiled. It saves your data in the browser cache, so as long as you don't clear it your data will not be lost.

**Comment by angel-carvajal-coder** [comment]
Oh, I'm running an HP Elite 5000 (quite old, yes) with Linux Mint.
The thing is that I have ran the simulation on Windows 10 on the same computer WITHOUT any issues! Also, yes, I **have** tried out the web version, but the extra chips (keyboard, eeprom, hdd, display,...) distract me and make it so that I have to move the slider all the way to the right if I want to use my chips.
