### ISSUE TITLE
OR Gate

### ISSUE THREAD

**Issue by CheeseTastisch** [SebLague/Digital-Logic-Sim#76]
Hey,

i think this is an cool programm.
But i would like to have a OR Gate default implemented (like AND & NOT Gate)

**Comment by Ibnelaiq** [comment]
Yeah, but it is more fun to create OR Gate from NAND Gates 

OR GATE: 
![Screenshot (127)](https://user-images.githubusercontent.com/58213692/123539923-9eb84300-d755-11eb-81a8-be93ab5604b7.png)
NAND GATE:
![Screenshot (128)](https://user-images.githubusercontent.com/58213692/123539960-cc04f100-d755-11eb-8c52-e70f34a0cad9.png)

**Comment by CheeseTastisch** [comment]
Thanks for your answer.
The NAND gate at the beginning of the gate can be replaced with a simple NOT gate.
Because if you use tow times the same input for an AND gate, the input is always the output.
So if the AND gate (in the NAND gate) is called, it is not necessary in the end, since in this way only the NOT gate remains.

**Comment by Ibnelaiq** [comment]
Thanks for correcting me, You are 100% correct.

**Comment by diguifi** [comment]
I actually had fun figuring out how to make an OR gate from just ANDs and NOTs
