### ISSUE TITLE
How and Where can I delete the save data to the simulator on linux

### ISSUE THREAD

**Issue by Dell-Glitch** [SebLague/Digital-Logic-Sim#77]
I accidentally put the res settings too high

**Comment by Turnip1234** [comment]
`%appdata%\..\LocalLow\Sebastian Lague\Digital Logic Sim\SaveData`

**Comment by Turnip1234** [comment]
@Dell-Glitch

**Comment by Turnip1234** [comment]
There's just a txt file there for each of your chips, delete the one you don't want and restart Digital Logic Sim

**Comment by Dell-Glitch** [comment]
@Turnip1234 I forgot to say I'm on Linux

**Comment by Turnip1234** [comment]
Ah

**Comment by Turnip1234** [comment]
I think on Linux the path is `$XDG_CONFIG_HOME/unity3d/Sebastian Lague/Digital Logic Sim\SaveData` but I could be mistaken

**Comment by Turnip1234** [comment]
@Dell-Glitch

**Comment by Dell-Glitch** [comment]
thanks
