### ISSUE TITLE
App unusable because of very small window

### ISSUE THREAD

**Issue by Anay-v2** [SebLague/Digital-Logic-Sim#88]
Whenever I open this It opens it in a very small window which makes it unusable: 

![Capture](https://user-images.githubusercontent.com/87125465/144374873-8844a153-d101-4f9a-906a-06f0f04340d5.PNG)

It doesn't even let me maximize it.

**Comment by Xanderplayz17** [comment]
Resize it bro

**Comment by Anay-v2** [comment]
it doesnt allow me to

**Comment by Xanderplayz17** [comment]
Then idk
