### ISSUE TITLE
Chips saved in folder but not appearing when loading project

### ISSUE THREAD

**Issue by JRHauber** [SebLague/Digital-Logic-Sim#89]
The title is pretty self-explanatory, but I have chips who's .txt files are saved in the saves folder, but when I load the project in the app, they don't appear on the bottom tray for me to continue working with them.

**Comment by Turnip1234** [comment]
Hi @Lanidae! I have a couple of clarifying questions:
- Are there subdirectories in the `saves` folder for each project?
- What version of the app are  you using?
Thanks!

**Comment by Lanidae** [comment]
There are sub directories for each project and I'm using the one with compiled pull requests by A0x0 since I like many of the features it has.
