### ISSUE TITLE
After creating a logic gate on linux a lot of text gets messed up

### ISSUE THREAD

**Issue by BlockOG** [SebLague/Digital-Logic-Sim#9]
Here is before I placed a logic gate:
![Before_001](https://user-images.githubusercontent.com/68442822/101185845-0b091300-365b-11eb-8340-c11161218333.png)
And here is after I place a logic gate:
![After_001](https://user-images.githubusercontent.com/68442822/101185842-0a707c80-365b-11eb-8946-6d5e57e58c9a.png)
![After_001_1](https://user-images.githubusercontent.com/68442822/101185844-0b091300-365b-11eb-9f0a-646bcebebe4f.png)

**Comment by dhbahr** [comment]
I can also confirm this behavior

**Comment by SebLague** [comment]
Could anyone let me know if this is still the case in the latest build?

**Comment by Broken-Admin** [comment]
I am running Xubuntu, Ubuntu 20.04, kernel version 5.4.0-52.

I have no encountered this issue.

@dhbahr and @BlockOG, would you care to provide your system specifications and distribution? The `neofetch` package is very well at providing them. Your distributions may also have a provided package for system information.

**Comment by dhbahr** [comment]
@SebLague current build seems to have fixed it for me. Great stuff, mate!
@Broken-Admin I'm running Arch on 5.4.80-2-lts kernel, since you specifically asked for neofetch :P
```
$ neofetch             
                   -`                    dhbahr@pauarch 
                  .o+`                   -------------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: 20KN009QGE ThinkPad E480 
               `+oooooo:                 Kernel: 5.4.80-2-lts 
               -+oooooo+:                Uptime: 4 days, 4 hours, 21 mins 
             `/:-:++oooo+:               Packages: 1565 (pacman), 22 (flatpak) 
            `/++++/+++++++:              Shell: zsh 5.8 
           `/++++++++++++++:             Resolution: 1600x900, 1920x1080 
          `/+++ooooooooooooo/`           DE: GNOME 
         ./ooosssso++osssssso+`          WM: Mutter 
        .oossssso-````/ossssss+`         WM Theme: Adwaita 
       -osssssso.      :ssssssso.        Theme: Adwaita-dark [GTK2/3] 
      :osssssss/        osssso+++.       Icons: Papirus [GTK2/3] 
     /ossssssss/        +ssssooo/-       CPU: Intel i7-8550U (8) @ 4.000GHz 
   `/ossssso+/:-        -:/+osssso+-     GPU: AMD ATI Radeon 540/540X/550/550X / RX 540X/550/550X 
  `+sso+:-`                 `.-/+oso:    GPU: Intel UHD Graphics 620
 `++:.                           `-/+/   Memory: 13833MiB / 15777MiB
 .`                                 `/
                                                                 
                                                                 
```

**Comment by Broken-Admin** [comment]
Imagine using GNOME, although the Papyrus icons are great. But glad the latest fixed it! Cheers.

**Comment by SebLague** [comment]
Thanks for the response, happy it seems to be fixed!
